sonar.projectKey=bookshop-api-node
sonar.projectName=Bookshop API Node
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
